'use client';
import { useState, useEffect } from 'react';
import { Arrow } from './Atmosphere';
const routes=[{id:'hero',name:'The mountain path',note:'For a fresh perspective',image:'hero',duration:'A moment to look beyond'},{id:'tranquility',name:'The quiet waters',note:'For a slower kind of day',image:'waterfall',duration:'A moment to breathe'},{id:'biodiversity',name:'The living forest',note:'For your curious side',image:'forest',duration:'A moment to look closer'}];
export default function JourneyPlanner({onClose}:{onClose:()=>void}){
 const [name,setName]=useState('');const [route,setRoute]=useState('tranquility');const [saved,setSaved]=useState(false);const [storageError,setStorageError]=useState(false);
 useEffect(()=>{try{const prior=JSON.parse(localStorage.getItem('visite-journey-v1')||'null');if(prior){setName(prior.name||'');if(routes.some(r=>r.id===prior.route))setRoute(prior.route);}}catch{}},[]);
 const current=routes.find(r=>r.id===route)!;
 function save(e:React.FormEvent){e.preventDefault();try{localStorage.setItem('visite-journey-v1',JSON.stringify({name:name.trim(),route}));}catch{setStorageError(true);}setSaved(true);}
 function download(){const text=`YOUR NOTOSAN FIELD NOTES\n\n${name.trim()||'Fellow wanderer'}, make a little room for wonder.\n\nYour path: ${current.name}\n${current.duration}\n\n1. Take a deep breath before you begin.\n2. Follow the ${current.name.toLowerCase()} and notice one small detail.\n3. Explore the other chapters at your own pace.\n4. Carry that curiosity into the world outside.\n\nLeave only footprints. Take only memories.\n\nAn illustrated digital experience, not a real-world tour booking.\nhttps://visite-nature.kolligireeshkumarred.chatgpt.site\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='My-Notosan-Journey.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(saved)return <div className="plan-confirmation"><span className="eyebrow">YOUR NEXT CHAPTER</span><div className="confirmation-mark">✧</div><h2>{name.trim()?`${name.trim()}, your`:'Your'} journey awaits.</h2><p>{storageError?'Your path is ready. Download your field notes to keep a copy.':'Your favorite path is saved on this device. Come back whenever you need a little space.'}</p><div className="chosen-path"><img src={`/art/${current.image}.webp`} alt=""/><span>{current.name}<small>{current.note}</small></span></div><a href={`#${route}`} className="button button-light" onClick={onClose}>Follow your path <Arrow/></a><button className="text-link" onClick={download}>Download your field notes <Arrow diagonal/></button></div>;
 return <form onSubmit={save} className="planner"><span className="eyebrow">A JOURNEY, AT YOUR PACE</span><h2>Where will you<br/><em>find yourself?</em></h2><p>Choose the feeling you want to take with you.</p><fieldset className="route-options"><legend className="sr-only">Choose your path</legend>{routes.map(r=><label key={r.id} className={`route-option ${route===r.id?'selected':''}`}><input type="radio" name="route" value={r.id} checked={route===r.id} onChange={()=>setRoute(r.id)}/><img src={`/art/${r.image}.webp`} alt=""/><span>{r.name}<small>{r.note}</small></span><span className="radio-dot"/></label>)}</fieldset><label className="name-label" htmlFor="visitor-name">What should we call you? <span>(optional)</span></label><input id="visitor-name" className="name-input" placeholder="Your first name" maxLength={36} value={name} onChange={e=>setName(e.target.value)}/><button type="submit" className="button button-light">Save my journey <Arrow/></button><p className="privacy-note">A personal field journal, saved only in your browser. No account needed.</p></form>;
}
