'use client';
import { useState, useRef, useEffect } from 'react';
import { Birds, Particles, Reeds, Water, Arrow } from './Atmosphere';
import ExperienceDialog from './ExperienceDialog';
import JourneyPlanner from './JourneyPlanner';
import { useNatureMotion } from './useNatureMotion';
import LivingScene from './living/LivingScene';
const chapters=[{id:'hero',label:'The beginning'},{id:'tranquility',label:'Tranquility'},{id:'biodiversity',label:'Biodiversity'},{id:'field-notes',label:'Your journey'},{id:'care',label:'Tread lightly'}];
const stories:Record<string,{label:string;title:string;text:string[];image?:string}>={
 tranquility:{label:'01 / FIND YOUR STILLNESS',title:'There is a quiet kind of wonder.',image:'waterfall',text:['Follow the river beyond the last familiar bend. Here, the rush of water is the only clock you need, and the smallest moments have room to become something more.','Pause beside the falls. Watch a ripple disappear. Let the light move across the rocks. You don’t have to go anywhere to feel a little further from the everyday.','Try this: take three slow breaths, then look for a detail you missed the first time.']},
 biodiversity:{label:'02 / A WORLD, INTERCONNECTED',title:'Every life has a place.',image:'forest',text:['Beyond the first glance, the forest is full of stories. A leaf catching the last of the light. A deer stepping quietly through the undergrowth. Water finding its own way home.','These little encounters invite us to pay attention. When we make room for the living world, we discover how much there is to care for.','Explore the glowing points in the scene to meet the forest a little closer.']},
 wildlife:{label:'FIELD NOTE / WILDLIFE',title:'A quiet encounter.',image:'forest',text:['In our illustrated forest, the spotted deer is a reminder to stop and notice. Watch from a distance, give wildlife space, and let the moment belong to them.','Out in nature, never feed wild animals or try to approach them for a photograph. The most memorable encounter is often the one that leaves no trace.']},
 water:{label:'FIELD NOTE / WATER',title:'Follow the flow.',image:'waterfall',text:['From a small ripple to a waterfall, water gives this landscape its rhythm. Follow its path through all three chapters: the mountain lake, the quiet falls, and the forest stream.','Listen closely. What feels like silence is often a world of little sounds.']},
 flora:{label:'FIELD NOTE / PLANT LIFE',title:'Wonder, underfoot.',image:'forest',text:['Look down for a moment. Small flowers, soft moss, and unfurling leaves make a world of their own beneath the canopy.','Let wildflowers grow where you find them. A photograph or a sketch makes a lovely memory, without taking anything away.']},
 about:{label:'ABOUT THE EXPERIENCE',title:'A little closer to nature.',text:['Notosan · VISITE is an illustrated digital journey inspired by the calm and color of the natural world. Its three landscapes invite you to slow down, look closer, and rediscover your sense of wonder.','This is a creative website experience. The imagined landscapes are not real destinations, and the journey planner does not book a trip.']},
 privacy:{label:'YOUR PRIVACY',title:'Your journey stays yours.',text:['The journey planner saves your optional first name and chosen chapter in local storage on this browser. These details are not submitted to a server by this page.','You can remove this saved information using the button below, or by clearing this site’s browser data. The site’s hosting provider may process technical data needed to serve the page.']},
 access:{label:'ACCESSIBILITY',title:'Explore in your own way.',text:['Use the chapter links to move directly between scenes. All controls work with a keyboard, and dialogs close with Escape. Decorative images and effects are hidden from screen readers.','The experience follows your device’s reduced-motion setting: smooth scrolling, moving water, floating particles, and scroll animations are disabled when reduced motion is enabled. Sound is off until you choose to turn it on.']}
};
const careNotes=[{title:'Take the quieter path.',text:'Keep to established trails, give wildlife plenty of space, and let the sounds of the landscape lead the way.'},{title:'Let the wild stay wild.',text:'Leave flowers, stones, and little discoveries where they belong. Carry the memory home in a photograph, a sketch, or a story.'},{title:'Leave it a little better.',text:'Take everything you brought with you, including litter. Small acts of care help keep beautiful places beautiful.'}];
export default function NatureExperience(){
 const root=useRef<HTMLDivElement>(null);const [chapter,setChapter]=useState('hero');const [dialog,setDialog]=useState<string|null>(null);const [menu,setMenu]=useState(false);const [sound,setSound]=useState(false);const [notice,setNotice]=useState('');const audio=useRef<AudioContext|null>(null);
 useNatureMotion(root,setChapter);
 useEffect(()=>()=>{void audio.current?.close();},[]);
 async function toggleSound(){try{if(sound){await audio.current?.suspend();setSound(false);return;}if(!audio.current){const ctx=new AudioContext();audio.current=ctx;const buffer=ctx.createBuffer(1,ctx.sampleRate*4,ctx.sampleRate);const data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+0.02*(Math.random()*2-1))/1.02;data[i]=last*3.5;}const source=ctx.createBufferSource();source.buffer=buffer;source.loop=true;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=550;const gain=ctx.createGain();gain.gain.value=0.09;source.connect(filter).connect(gain).connect(ctx.destination);source.start();}await audio.current.resume();setSound(true);}catch{setNotice('Ambient sound is unavailable in this browser.');}}
 const close=()=>setDialog(null);
 return <div ref={root} className="experience">
 <a href="#main" className="skip-link">Skip to content</a><div className="reading-progress" aria-hidden="true"/>
 <header className={`site-header ${chapter!=='hero'?'header-dark':''}`}><a href="#hero" className="brand" aria-label="Notosan home">Notosan<span className="brand-dot">®</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#tranquility">The journey</a><a href="#story">About</a><a href="#care">Our promise</a><a href="#field-notes">Field notes</a></nav><button className="nav-cta" onClick={()=>setDialog('planner')}>Plan your visit <Arrow diagonal/></button><button className={`menu-toggle ${menu?'is-open':''}`} aria-label="Open navigation" aria-expanded={menu} onClick={()=>setMenu(true)}><span/><span/></button></header>
 <main id="main">
 <section id="hero" className="hero scene" aria-labelledby="hero-title"><div className="scene-art parallax-art"><picture><source media="(max-width: 760px)" srcSet="/art/hero-mobile.webp"/><img src="/art/hero.webp" alt="Golden mountains above a violet lake, with a red-cloaked traveler looking out from a grassy hill." fetchPriority="high" width="1672" height="941"/></picture><LivingScene scene="hero"/><div className="hero-glow"/></div><div className="hero-shade"/><Particles/><Birds variant="hero-birds"/>
 <div className="hero-copy"><p className="eyebrow"><span className="little-mountains">♧</span> A JOURNEY BEYOND THE EVERYDAY</p><h1 id="hero-title" className="hero-word" aria-label="Visite">{'VISITE'.split('').map((letter,i)=><span key={i} aria-hidden="true">{letter}</span>)}</h1><p className="hero-description">Somewhere between the mountains and the sky,<br className="desktop-break"/> a different kind of journey begins.<br/>Step into nature. Come back to yourself.</p><div className="hero-actions"><a href="#tranquility" className="button button-light">Start the journey <Arrow/></a><span className="hero-small">Let curiosity lead.</span></div></div>
 <div className="hero-bottom"><a className="scroll-cue" href="#tranquility"><span className="scroll-line"/>SCROLL TO WANDER</a><span className="hero-location">A WORLD WORTH GETTING LOST IN <span>01 — 03</span></span></div><Reeds/>
 </section>
 <section id="tranquility" className="scene tranquility" aria-labelledby="tranquility-title"><div className="scene-art parallax-art"><picture><source media="(max-width: 760px)" srcSet="/art/waterfall-mobile.webp"/><img src="/art/waterfall.webp" alt="An illustrated traveler rests by luminous falls in a secluded purple forest." loading="lazy" width="1672" height="941"/></picture><LivingScene scene="waterfall"/></div><div className="scene-top-fade"/><Water side="left"/><Particles/><Birds variant="waterfall-birds"/><div className="scene-copy copy-right"><span className="eyebrow reveal">01 / A MOMENT TO BREATHE</span><h2 id="tranquility-title" className="reveal">Tranquility</h2><p className="reveal">Beyond the noise, a softer world awaits. Follow the water, feel the light, and let the everyday drift a little further away.</p><p className="reveal secondary-copy">There is no rush here. Just the quiet joy of being exactly where you are.</p><button className="text-link reveal" onClick={()=>setDialog('tranquility')}><span className="link-line"/>Learn more <Arrow/></button></div><span className="scene-caption">THE SOUND OF DOING NOTHING.</span><Reeds/>
 </section>
 <section id="biodiversity" className="scene biodiversity" aria-labelledby="biodiversity-title"><div className="scene-art parallax-art"><picture><source media="(max-width: 760px)" srcSet="/art/forest-mobile.webp"/><img src="/art/forest.webp" alt="A spotted deer beside a forest waterfall, surrounded by lavender rocks, flowers and ferns." loading="lazy" width="1672" height="941"/></picture><LivingScene scene="forest"/></div><div className="scene-top-fade"/><Water side="right"/><Particles/><div className="scene-copy copy-left"><span className="eyebrow reveal">02 / LOOK A LITTLE CLOSER</span><h2 id="biodiversity-title" className="reveal">Biodiversity</h2><p className="reveal">A thousand little stories, living side by side. From the smallest wildflower to the quietest footsteps, every life belongs to something bigger.</p><p className="reveal secondary-copy">Discover a world that asks for nothing but your attention. And perhaps, a little care.</p><button className="text-link reveal" onClick={()=>setDialog('biodiversity')}><span className="link-line"/>Learn more <Arrow/></button></div>
 <div className="nature-hotspots"><button className="hotspot spot-deer" onClick={()=>setDialog('wildlife')} aria-label="Discover the forest wildlife"><span>+</span><small>A quiet encounter</small></button><button className="hotspot spot-flower" onClick={()=>setDialog('flora')} aria-label="Discover the forest plant life"><span>+</span><small>Wonder, underfoot</small></button><button className="hotspot spot-water" onClick={()=>setDialog('water')} aria-label="Discover the waterfall"><span>+</span><small>Follow the flow</small></button></div><span className="scene-caption">TOUCH A LITTLE WONDER. EXPLORE THE GLOWING POINTS.</span><Reeds/>
 </section>
 <section id="story" className="manifesto section-space" aria-labelledby="story-title"><div className="manifesto-orbit" aria-hidden="true"><span>✧</span></div><p className="eyebrow reveal">THE ART OF PAYING ATTENTION</p><h2 id="story-title"><span className="manifesto-line">You don’t always need</span><span className="manifesto-line">to go <em>further.</em></span><span className="manifesto-line">Sometimes, you just need</span><span className="manifesto-line">to look <em>closer.</em></span></h2><div className="manifesto-bottom reveal"><span className="tiny-star">✳</span><p>A slower step. A deeper breath. A small reminder<br className="desktop-break"/> that we are part of something wonderful.</p></div></section>
 <section id="field-notes" className="field-notes section-space" aria-labelledby="field-title"><div className="section-heading"><div><p className="eyebrow reveal">03 / FOLLOW YOUR CURIOSITY</p><h2 id="field-title" className="reveal">Find your <em>kind of wonder.</em></h2></div><p className="section-intro reveal">Every path has a different rhythm.<br/>Which one feels like you?</p></div><div className="path-grid">{[{n:'01',id:'hero',title:'Chase the horizon',sub:'THE MOUNTAIN PATH',art:'hero'},{n:'02',id:'tranquility',title:'Find your stillness',sub:'THE QUIET WATERS',art:'waterfall'},{n:'03',id:'biodiversity',title:'Meet the wild',sub:'THE LIVING FOREST',art:'forest'}].map(path=><a href={`#${path.id}`} className="path-card reveal" key={path.n}><img src={`/art/${path.art}.webp`} alt="" loading="lazy"/><div className="path-card-shade"/><div className="path-top"><span>{path.n}</span><span className="round-arrow"><Arrow diagonal/></span></div><div className="path-info"><span className="eyebrow">{path.sub}</span><h3>{path.title}</h3><span className="path-explore">Explore this chapter <Arrow/></span></div></a>)}</div><div className="field-notes-foot reveal"><p>No destination to tick off. Just a feeling to follow.</p><button className="text-link" onClick={()=>setDialog('planner')}>Create your own journey <Arrow diagonal/></button></div></section>
 <section id="care" className="care section-space" aria-labelledby="care-title"><div className="care-intro reveal"><span className="eyebrow">WONDER IS WORTH PROTECTING</span><h2 id="care-title">Leave only<br/><em>footprints.</em></h2><p>Beautiful places stay beautiful when we care for them. Carry a little of that care into your next adventure.</p><div className="care-symbol" aria-hidden="true"><svg viewBox="0 0 120 120"><path d="M60 106V42m0 30C27 73 17 42 26 16 60 22 69 43 60 65m1 21c29-3 46-23 39-48-26 1-43 21-39 42" fill="none" stroke="currentColor" strokeWidth="1"/></svg><span>TAKE MEMORIES.<br/>LEAVE WONDER.</span></div></div><div className="care-notes reveal">{careNotes.map((note,i)=><details key={note.title} open={i===0?true:undefined}><summary><span className="note-number">0{i+1}</span><h3>{note.title}</h3><span className="details-plus"/></summary><p>{note.text}</p></details>)}<p className="care-postscript">Small gestures. A world of difference.</p></div></section>
 <section id="begin" className="closing scene" aria-labelledby="closing-title"><div className="scene-art parallax-art"><picture><source media="(max-width: 760px)" srcSet="/art/hero-mobile.webp"/><img src="/art/hero.webp" alt="" loading="lazy" width="1672" height="941"/></picture><LivingScene scene="hero"/></div><div className="closing-shade"/><Particles/><div className="closing-copy"><p className="eyebrow reveal">THE WORLD IS STILL FULL OF WONDER</p><h2 id="closing-title" className="reveal">Go a little slower.<br/><em>Feel a little more.</em></h2><p className="reveal">Your next chapter begins with a single step.</p><button className="button button-light reveal" onClick={()=>setDialog('planner')}>Begin your own journey <Arrow/></button></div><Reeds/></section>
 </main>
 <footer id="footer" className="site-footer"><div className="footer-top"><div><a href="#hero" className="brand">Notosan<span className="brand-dot">®</span></a><p>A little closer to nature.<br/>A little closer to yourself.</p></div><div className="footer-links"><span className="eyebrow">KEEP WANDERING</span><a href="#tranquility">Tranquility</a><a href="#biodiversity">Biodiversity</a><a href="#field-notes">Find your path</a></div><div className="footer-links"><span className="eyebrow">A LITTLE MORE</span><button onClick={()=>setDialog('about')}>About this experience</button><button onClick={()=>setDialog('access')}>Accessibility</button><button onClick={()=>setDialog('privacy')}>Privacy & your journal</button></div><a className="back-top" href="#hero" aria-label="Return to top"><Arrow/> <span>BACK TO THE BEGINNING</span></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Notosan · VISITE</span><span>AN ILLUSTRATED JOURNEY. MADE FOR THE WANDERER IN YOU.</span><span>TAKE YOUR TIME. ✧</span></div></footer>
 <nav className="chapter-nav" aria-label="Chapter navigation">{chapters.map((c,i)=><a key={c.id} href={`#${c.id}`} className={chapter===c.id?'active':''} aria-label={`Chapter ${i+1}: ${c.label}`} aria-current={chapter===c.id?'location':undefined}><span className="chapter-label">{c.label}</span><i/></a>)}</nav>
 <button className={`sound-toggle ${sound?'sound-on':''}`} onClick={toggleSound} aria-pressed={sound} aria-label={sound?'Turn ambient sound off':'Turn ambient sound on'}><span className="sound-bars" aria-hidden="true"><i/><i/><i/><i/></span><span>SOUND {sound?'ON':'OFF'}</span></button><div className="live-notice sr-only" aria-live="polite">{notice}</div>
 {menu?<ExperienceDialog title="Navigation" onClose={()=>setMenu(false)} className="menu-dialog"><span className="eyebrow">NOTOSAN / YOUR JOURNEY</span><nav className="mobile-nav" aria-label="Mobile navigation">{chapters.map((c,i)=><a href={`#${c.id}`} key={c.id} onClick={()=>setMenu(false)}><small>0{i+1}</small>{c.label}<Arrow/></a>)}</nav><button className="button button-light" onClick={()=>{setMenu(false);setDialog('planner');}}>Plan your visit <Arrow/></button></ExperienceDialog>:null}
 {dialog?<ExperienceDialog title={dialog==='planner'?'Plan your visit':stories[dialog]?.title||'Details'} onClose={close}>{dialog==='planner'?<JourneyPlanner onClose={close}/>:<article className="story-dialog">{stories[dialog]?.image?<img className="dialog-art" src={`/art/${stories[dialog].image}.webp`} alt=""/>:null}<div className="story-dialog-copy"><span className="eyebrow">{stories[dialog]?.label}</span><h2>{stories[dialog]?.title}</h2>{stories[dialog]?.text.map(p=><p key={p}>{p}</p>)}{dialog==='privacy'?<button className="text-link" onClick={()=>{try{localStorage.removeItem('visite-journey-v1');setNotice('Your saved journey has been removed.');}catch{setNotice('Could not access this browser’s saved data.');}}}>Clear my saved journey <Arrow/></button>:null}{dialog==='privacy'?<p className="form-notice" role="status">{notice}</p>:null}<button className="button button-outline" onClick={close}>Back to the journey <Arrow/></button></div></article>}</ExperienceDialog>:null}
 </div>;
}
