// Generated by scripts/living-art/build.py. Do not edit by hand.
export const ART_MANIFEST = {
 "hero": {
  "size": [
   1672,
   941
  ],
  "features": {
   "cloud": true,
   "cloth": true,
   "mist": "drift",
   "stars": true,
   "glow": "sun"
  },
  "flock": [
   {
    "x": 538,
    "y": 331,
    "s": 42,
    "glide": 0
   },
   {
    "x": 635,
    "y": 358,
    "s": 42,
    "glide": 0
   },
   {
    "x": 718,
    "y": 314,
    "s": 54,
    "glide": 1
   },
   {
    "x": 737,
    "y": 357,
    "s": 36,
    "glide": 0
   },
   {
    "x": 802,
    "y": 318,
    "s": 34,
    "glide": 0
   },
   {
    "x": 797,
    "y": 338,
    "s": 34,
    "glide": 0
   },
   {
    "x": 848,
    "y": 312,
    "s": 30,
    "glide": 0
   },
   {
    "x": 875,
    "y": 342,
    "s": 48,
    "glide": 1
   },
   {
    "x": 956,
    "y": 340,
    "s": 32,
    "glide": 0
   },
   {
    "x": 1005,
    "y": 321,
    "s": 46,
    "glide": 0
   },
   {
    "x": 1060,
    "y": 313,
    "s": 32,
    "glide": 1
   }
  ],
  "plate": "/art/live/hero-plate.webp",
  "ctrl": "/art/live/hero-ctrl.png",
  "puppets": {
   "travBreath": {
    "c": [
     1362.0,
     640.0
    ],
    "ax": [
     95.0,
     150.0
    ],
    "angle": 0.0,
    "pivot": [
     1365.0,
     772.0
    ],
    "feather": 0.35,
    "taper": 0
   },
   "travHat": {
    "c": [
     1360.0,
     506.0
    ],
    "ax": [
     100.0,
     46.0
    ],
    "angle": 0.0,
    "pivot": [
     1358.0,
     550.0
    ],
    "feather": 0.3,
    "taper": 0
   }
  }
 },
 "hero-mobile": {
  "size": [
   1024,
   1536
  ],
  "features": {
   "cloud": true,
   "cloth": true,
   "mist": "drift",
   "stars": true,
   "glow": "sun"
  },
  "flock": [
   {
    "x": 203,
    "y": 781,
    "s": 30,
    "glide": 0
   },
   {
    "x": 287,
    "y": 814,
    "s": 32,
    "glide": 0
   },
   {
    "x": 358,
    "y": 772,
    "s": 46,
    "glide": 1
   },
   {
    "x": 374,
    "y": 813,
    "s": 28,
    "glide": 0
   },
   {
    "x": 425,
    "y": 780,
    "s": 30,
    "glide": 0
   },
   {
    "x": 424,
    "y": 798,
    "s": 30,
    "glide": 0
   },
   {
    "x": 460,
    "y": 771,
    "s": 18,
    "glide": 0
   },
   {
    "x": 478,
    "y": 803,
    "s": 42,
    "glide": 1
   },
   {
    "x": 532,
    "y": 804,
    "s": 24,
    "glide": 0
   },
   {
    "x": 572,
    "y": 788,
    "s": 36,
    "glide": 0
   }
  ],
  "plate": "/art/live/hero-mobile-plate.webp",
  "ctrl": "/art/live/hero-mobile-ctrl.png",
  "puppets": {
   "travBreath": {
    "c": [
     830.0,
     1192.0
    ],
    "ax": [
     72.0,
     110.0
    ],
    "angle": 0.0,
    "pivot": [
     832.0,
     1298.0
    ],
    "feather": 0.35,
    "taper": 0
   },
   "travHat": {
    "c": [
     828.0,
     1106.0
    ],
    "ax": [
     64.0,
     26.0
    ],
    "angle": 0.0,
    "pivot": [
     826.0,
     1130.0
    ],
    "feather": 0.3,
    "taper": 0
   }
  }
 },
 "waterfall": {
  "size": [
   1672,
   941
  ],
  "features": {
   "flow": true,
   "mist": "rise",
   "glow": "rays"
  },
  "plate": "/art/waterfall.webp",
  "ctrl": "/art/live/waterfall-ctrl.png",
  "puppets": {
   "fishBreath": {
    "c": [
     1300.0,
     642.0
    ],
    "ax": [
     82.0,
     76.0
    ],
    "angle": 0.0,
    "pivot": [
     1290.0,
     706.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "fishHead": {
    "c": [
     1293.0,
     592.0
    ],
    "ax": [
     84.0,
     54.0
    ],
    "angle": 0.0,
    "pivot": [
     1290.0,
     642.0
    ],
    "feather": 0.35,
    "taper": 0
   },
   "rod": {
    "c": [
     1198.0,
     616.0
    ],
    "ax": [
     92.0,
     11.0
    ],
    "angle": 0.5899,
    "pivot": [
     1266.0,
     662.0
    ],
    "feather": 0.45,
    "taper": 0
   },
   "line": {
    "c": [
     1024.0,
     704.0
    ],
    "ax": [
     178.0,
     30.0
    ],
    "angle": 2.248,
    "pivot": [
     1130.0,
     571.0
    ],
    "feather": 0.3,
    "taper": 1
   },
   "footL": {
    "c": [
     1218.0,
     720.0
    ],
    "ax": [
     25.0,
     21.0
    ],
    "angle": 0.0,
    "pivot": [
     1236.0,
     698.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "footR": {
    "c": [
     1259.0,
     736.0
    ],
    "ax": [
     27.0,
     22.0
    ],
    "angle": 0.0,
    "pivot": [
     1278.0,
     712.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "doveA": {
    "c": [
     537.0,
     636.0
    ],
    "ax": [
     66.0,
     44.0
    ],
    "angle": 0.0,
    "pivot": [
     537.0,
     630.0
    ],
    "feather": 0.35,
    "taper": 0
   },
   "doveAL": {
    "c": [
     502.0,
     613.0
    ],
    "ax": [
     30.0,
     13.0
    ],
    "angle": -0.2618,
    "pivot": [
     528.0,
     624.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "doveAR": {
    "c": [
     572.0,
     613.0
    ],
    "ax": [
     30.0,
     13.0
    ],
    "angle": 0.2618,
    "pivot": [
     546.0,
     624.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "doveB": {
    "c": [
     280.0,
     757.0
    ],
    "ax": [
     74.0,
     28.0
    ],
    "angle": 0.0,
    "pivot": [
     288.0,
     752.0
    ],
    "feather": 0.35,
    "taper": 0
   },
   "doveBL": {
    "c": [
     240.0,
     749.0
    ],
    "ax": [
     36.0,
     11.0
    ],
    "angle": 0.0,
    "pivot": [
     276.0,
     752.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "doveC": {
    "c": [
     482.0,
     797.0
    ],
    "ax": [
     46.0,
     32.0
    ],
    "angle": 0.0,
    "pivot": [
     484.0,
     793.0
    ],
    "feather": 0.35,
    "taper": 0
   },
   "doveCL": {
    "c": [
     456.0,
     788.0
    ],
    "ax": [
     20.0,
     11.0
    ],
    "angle": -0.4363,
    "pivot": [
     474.0,
     795.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "doveD": {
    "c": [
     368.0,
     566.0
    ],
    "ax": [
     20.0,
     14.0
    ],
    "angle": 0.0,
    "pivot": [
     368.0,
     566.0
    ],
    "feather": 0.35,
    "taper": 0
   }
  },
  "fisher": {
   "hands": [
    1266.0,
    662.0
   ],
   "tip": [
    1130.0,
    571.0
   ],
   "entry": [
    915.0,
    838.0
   ]
  },
  "rayDir": [
   1.0,
   0.6
  ]
 },
 "waterfall-mobile": {
  "size": [
   1024,
   1536
  ],
  "features": {
   "flow": true,
   "mist": "rise",
   "glow": "rays"
  },
  "plate": "/art/waterfall-mobile.webp",
  "ctrl": "/art/live/waterfall-mobile-ctrl.png",
  "puppets": {
   "fishBreath": {
    "c": [
     790.0,
     1162.0
    ],
    "ax": [
     62.0,
     56.0
    ],
    "angle": 0.0,
    "pivot": [
     785.0,
     1206.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "fishHead": {
    "c": [
     785.0,
     1106.0
    ],
    "ax": [
     58.0,
     40.0
    ],
    "angle": 0.0,
    "pivot": [
     780.0,
     1150.0
    ],
    "feather": 0.35,
    "taper": 0
   },
   "rod": {
    "c": [
     719.0,
     1112.0
    ],
    "ax": [
     62.0,
     9.0
    ],
    "angle": 0.5533,
    "pivot": [
     770.0,
     1143.0
    ],
    "feather": 0.45,
    "taper": 0
   },
   "line": {
    "c": [
     582.0,
     1208.0
    ],
    "ax": [
     160.0,
     24.0
    ],
    "angle": 2.1677,
    "pivot": [
     668.0,
     1080.0
    ],
    "feather": 0.3,
    "taper": 1
   },
   "footL": {
    "c": [
     740.0,
     1214.0
    ],
    "ax": [
     19.0,
     15.0
    ],
    "angle": 0.0,
    "pivot": [
     752.0,
     1196.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "footR": {
    "c": [
     772.0,
     1222.0
    ],
    "ax": [
     19.0,
     15.0
    ],
    "angle": 0.0,
    "pivot": [
     786.0,
     1201.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "doveA": {
    "c": [
     266.0,
     1141.0
    ],
    "ax": [
     54.0,
     38.0
    ],
    "angle": 0.0,
    "pivot": [
     266.0,
     1138.0
    ],
    "feather": 0.35,
    "taper": 0
   },
   "doveAL": {
    "c": [
     236.0,
     1122.0
    ],
    "ax": [
     24.0,
     10.0
    ],
    "angle": -0.3491,
    "pivot": [
     258.0,
     1134.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "doveAR": {
    "c": [
     296.0,
     1120.0
    ],
    "ax": [
     24.0,
     10.0
    ],
    "angle": 0.3491,
    "pivot": [
     274.0,
     1134.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "doveB": {
    "c": [
     118.0,
     1287.0
    ],
    "ax": [
     44.0,
     28.0
    ],
    "angle": 0.0,
    "pivot": [
     118.0,
     1285.0
    ],
    "feather": 0.35,
    "taper": 0
   },
   "doveBL": {
    "c": [
     95.0,
     1280.0
    ],
    "ax": [
     18.0,
     9.0
    ],
    "angle": -0.2618,
    "pivot": [
     112.0,
     1286.0
    ],
    "feather": 0.4,
    "taper": 0
   }
  },
  "fisher": {
   "hands": [
    770.0,
    1143.0
   ],
   "tip": [
    668.0,
    1080.0
   ],
   "entry": [
    495.0,
    1335.0
   ]
  },
  "rayDir": [
   1.0,
   0.8
  ]
 },
 "forest": {
  "size": [
   1672,
   941
  ],
  "features": {
   "flow": true,
   "mist": "rise",
   "deer": true
  },
  "deer": {
   "sprite": "/art/live/forest-deer.png",
   "rect": [
    926,
    457,
    213,
    272
   ],
   "cut": [
    [
     1032.0,
     736.0
    ],
    [
     1114.0,
     572.0
    ]
   ],
   "blend": 46,
   "shoulder": [
    1080.0,
    660.0
   ],
   "jaw": [
    [
     988.0,
     626.0
    ],
    [
     1072.0,
     606.0
    ]
   ],
   "head": [
    1032.0,
    572.0
   ],
   "eyes": [
    [
     1005.0,
     569.0
    ],
    [
     1045.0,
     569.0
    ]
   ],
   "eyeR": [
    8.0,
    6.0
   ],
   "ears": [
    {
     "base": [
      992.0,
      540.0
     ],
     "tip": [
      955.0,
      488.0
     ]
    },
    {
     "base": [
      1048.0,
      540.0
     ],
     "tip": [
      1083.0,
      488.0
     ]
    }
   ],
   "nose": [
    1040.0,
    603.0
   ]
  },
  "plate": "/art/live/forest-plate.webp",
  "ctrl": "/art/live/forest-ctrl.png",
  "puppets": {
   "deerBreath": {
    "c": [
     1205.0,
     650.0
    ],
    "ax": [
     165.0,
     92.0
    ],
    "angle": 0.0,
    "pivot": [
     1220.0,
     832.0
    ],
    "feather": 0.3,
    "taper": 0
   },
   "tail": {
    "c": [
     1352.0,
     642.0
    ],
    "ax": [
     24.0,
     48.0
    ],
    "angle": 0.0,
    "pivot": [
     1345.0,
     598.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "bush": {
    "c": [
     952.0,
     590.0
    ],
    "ax": [
     56.0,
     42.0
    ],
    "angle": 0.0,
    "pivot": [
     952.0,
     628.0
    ],
    "feather": 0.4,
    "taper": 0
   }
  }
 },
 "forest-mobile": {
  "size": [
   1024,
   1536
  ],
  "features": {
   "flow": true,
   "mist": "rise",
   "deer": true
  },
  "deer": {
   "sprite": "/art/live/forest-mobile-deer.png",
   "rect": [
    524,
    1017,
    176,
    237
   ],
   "cut": [
    [
     634.0,
     1238.0
    ],
    [
     670.0,
     1124.0
    ]
   ],
   "blend": 37,
   "shoulder": [
    650.0,
    1186.0
   ],
   "jaw": [
    [
     572.0,
     1158.0
    ],
    [
     642.0,
     1146.0
    ]
   ],
   "head": [
    602.0,
    1104.0
   ],
   "eyes": [
    [
     590.0,
     1112.0
    ],
    [
     623.0,
     1110.0
    ]
   ],
   "eyeR": [
    7.0,
    5.0
   ],
   "ears": [
    {
     "base": [
      586.0,
      1086.0
     ],
     "tip": [
      553.0,
      1043.0
     ]
    },
    {
     "base": [
      624.0,
      1084.0
     ],
     "tip": [
      651.0,
      1046.0
     ]
    }
   ],
   "nose": [
    617.0,
    1140.0
   ]
  },
  "plate": "/art/live/forest-mobile-plate.webp",
  "ctrl": "/art/live/forest-mobile-ctrl.png",
  "puppets": {
   "deerBreath": {
    "c": [
     742.0,
     1190.0
    ],
    "ax": [
     132.0,
     72.0
    ],
    "angle": 0.0,
    "pivot": [
     752.0,
     1342.0
    ],
    "feather": 0.3,
    "taper": 0
   },
   "tail": {
    "c": [
     866.0,
     1166.0
    ],
    "ax": [
     17.0,
     38.0
    ],
    "angle": 0.0,
    "pivot": [
     858.0,
     1134.0
    ],
    "feather": 0.4,
    "taper": 0
   },
   "bush": {
    "c": [
     506.0,
     1102.0
    ],
    "ax": [
     42.0,
     34.0
    ],
    "angle": 0.0,
    "pivot": [
     506.0,
     1132.0
    ],
    "feather": 0.4,
    "taper": 0
   }
  }
 }
} as const;
